New Code review branch
userman95/members-only pull request #2
Opened 2019-05-09 13:15 UTC by userman95

2019-05-10 01:21 UTC, rvvergara requested changes
Hi @userman95,

We still need some more work. Please see comments in the code. Also I want to raise out a point here:

![image](https://user-images.githubusercontent.com/6015315/57496296-c3969580-7304-11e9-99d4-00319d6fd841.png)

You have two separate views files for unauthenticated users (`views/posts/index.html.erb`) and logged users (`/views/all_posts.html.erb`). Why didn't we just have one file for them and just conditionally show the author name whenever there is a `current_user`?  Please do it that way as there is code repetition between the two files. 

Also please see my specific comment on using a partial instead of writing an `each` statement to show post details.

2019-05-10 01:21 UTC, rvvergara commented on app/views/posts/index.html.erb
> +      <% @posts.each do |post| %>
There's a simpler and a much better way to render a collection - use partials. For your posts I suggest you do this. Please refer to section 3.4.8 in this page of [Rails Guides](https://guides.rubyonrails.org/v5.2/layouts_and_rendering.html).

Essentially instead of having an `each` statement here for your posts you will simply use `<%= render '<directory you put this partial>/post' {<any local variable you wish to pass into it} %>`

2019-05-10 01:21 UTC, rvvergara commented on app/views/layouts/application.html.erb
> +  <body>
Why don't you put here login and logout links? It's much easier for users to be able to login and logout from anywhere in your page. Please don't forget that for this a logged in user shouldn't be seeing any "Login" link and a non-logged in user shouldn't be seeing "LogOut" link.

2019-05-10 01:21 UTC, rvvergara commented on app/views/users/new.html.erb
> +      <%= f.label :password %>
![image](https://user-images.githubusercontent.com/6015315/57496199-44a15d00-7304-11e9-8dec-12739c149a06.png)

Why am I seeing the password that I am typing here? You will see the reason in line 15. Please correct accordingly

2019-05-10 01:21 UTC, rvvergara commented on app/views/users/new.html.erb
> +      <%= f.text_field :password_confirmation,class: "form-control" %>
![image](https://user-images.githubusercontent.com/6015315/57496224-64388580-7304-11e9-98db-b58cbfcd28f8.png)

The same issue here. I shouldn't be seeing the password I am typing. This line offers you the clue as to why this is happening

2019-05-10 13:09 UTC, userman95 commented on app/views/posts/index.html.erb
> +      <% @posts.each do |post| %>
i created a new action `all_posts` because i wanted an unauthenticated user not to be able to see the usernames of the show all posts page . But when  he is logged in he should be able to see them  . I cant find a way to use partials and navigate a user through a link_to tag . As far as i read this more like a AJAX request and i didnt want to complicate the things too much . Thus i created the all_posts action . Of course i can use partials to have users see their posts (_post.html.erb)  but how i use link_to a partial?

2019-05-10 13:14 UTC, rvvergara commented on app/views/posts/index.html.erb
> +      <% @posts.each do |post| %>
No need for Ajax to do this. When we did this project we accomplished it using rails alone:

![image](https://user-images.githubusercontent.com/6015315/57529877-882db280-7368-11e9-93f4-803b8d16bbed.png)

That's inside our post partial. You can do it :)

2019-05-10 14:05 UTC, userman95 commented on app/views/posts/index.html.erb
> +      <% @posts.each do |post| %>
this is what i want to achieve for a logged in user 
![Screenshot (94)](https://user-images.githubusercontent.com/19325408/57532866-21e36880-7345-11e9-9cba-9df1db1ce881.png) 

![Screenshot (96)](https://user-images.githubusercontent.com/19325408/57532984-60792300-7345-11e9-8e7e-81733c148b31.png)


and this for a guest: 

![Screenshot (95)](https://user-images.githubusercontent.com/19325408/57533025-6e2ea880-7345-11e9-8022-302136185921.png)

I don't know if i understand you correctly , i know how to show a single page with logged in users and guests but i cant accomplish what i want only with the if statement . A path and a link_to that path i think is what  i need

2019-05-11 00:03 UTC, rvvergara commented on app/views/posts/index.html.erb
> +      <% @posts.each do |post| %>
Hi @userman95,

I do understand what it is you need to achieve. You want to only show the post author for logged users. Otherwise, if the user isn't logged on, you won't show it. 

Now to achieve that what you are doing is creating two separate files to list your posts - one for logged users and one for non-logged users. Question is, which part of your project decides which one to show? There is a file in your project that has that `if else` logic (i.e, the file that says 'if user is logged in render this file, else render that file`). What you need to do then is just replace that logic with this 'if user is logged on then show this line, else don't show this line'. That's a lot simpler and doesn't have any duplicated code in it. I already showed you how to do it. For details and further help I suggest you refer to the learning materials from Odin and Pathwright and use StackOverflow. Further you may consult with your mentor on how to do this. He/she would be familiar with it as he/she also should have done the project before.

2019-05-13 01:15 UTC, rvvergara approved these changes
Hi @userman95,

Now it's all good! :) Great job! I hope you learned something from that last change we talked about. Rails is about DRY code and creating two similar view files for conditionally showing elements on the page when you could simply use conditional statements for that particular element (in this case the post author) violates this DRY principle. 

I still notice files that shouldn't be included in git monitoring but they are (like some .tmp files still being watched by git). I'm not sure how you started this project but running `rails new` should have given you a default .gitignore. When I first checked this project you didn't have a `.gitignore` file at all. So pls in your future rails projects before you create any repository run `rails new` first.

Aside from the proper .gitignore there isn't anything more I require you to change. Please remember all the things we talked about in this project in building your succeeding projects. For now, you may already merge this into your Master branch and submit a code review completion form.

# :+1:

2019-05-13 07:14 UTC, merged